version: '3.8'

services:
  app:
    image: unionblack/devops-for-developers-project-74
    build:
      context: .
      dockerfile: Dockerfile.production
    command: make test
    # Передаем настройки подключения к базе данных прямо в контейнер тестов
    environment:
      - DATABASE_HOST=db
      - DATABASE_NAME=postgres
      - DATABASE_USERNAME=postgres
      - DATABASE_PASSWORD=password
    depends_on:
      db:
        condition: service_healthy

  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: postgres
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
