name: CI

on:
  push:
    branches:
      - main
      - master

jobs:
  test-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v7

      - name: Run tests
        run: docker compose -f docker-compose.yml up --abort-on-container-exit --exit-code-from app

      - name: Login to Docker Hub
        uses: docker/login-action@v4
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push production image
        uses: docker/build-push-action@v7
        with:
          context: .
          file: ./Dockerfile.production
          push: true
          tags: unionblack/devops-for-developers-project-74:latest
